# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Agent-global' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # pod 'AgoraRtcEngine_iOS', '4.5.0'
  pod 'SSZipArchive'
  pod 'SwiftyBeaver', '1.9.5'
  pod 'ZSwiftBaseLib', '0.1.6.2'
  pod 'AgoraRtcEngine_iOS', :path => 'sdk.podspec'
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']

  pod 'Common', :path => 'Common'

  # Agents
  pod 'VoiceAgent', :path => 'Scenes/VoiceAgent'
  
  pod 'Kingfisher'

end

target 'Agent-cn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
#  pod 'AgoraRtcEngine_iOS', '4.5.0'
  pod 'SSZipArchive'
  pod 'SwiftyBeaver', '1.9.5'
  pod 'ZSwiftBaseLib', '0.1.6.2'
  pod 'AgoraRtcEngine_iOS', :path => 'sdk.podspec'
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']

  pod 'Common', :path => 'Common'

  # Agents
  pod 'VoiceAgent', :path => 'Scenes/VoiceAgent'
  pod 'Kingfisher'
  
end
